version: '3.8'

services:
  fund-management:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # 数据持久化
      - ./fund_management.db:/app/fund_management.db  # 数据库文件映射
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl  # SSL证书目录
    depends_on:
      - fund-management
    restart: unless-stopped

volumes:
  data:
